name: Pipeline de Producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm test -- --coverage

      - name: Check coverage
        run: |
          npx nyc report --reporter=text
          if [ $(npx nyc report --reporter=text | grep -oP '(?<=All files\s+\|\s+)\d+') -lt 85 ]; then
            echo "Cobertura insuficiente (menos del 85%)"
            exit 1
          fi

      - name: Build Docker image
        run: docker build -t taller-autos .

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Desplegando a producción en Vercel..."
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --prod