name: Pipeline de Pruebas

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push a la rama main

jobs:
  test:
    runs-on: ubuntu-latest  # Usa una máquina virtual con Ubuntu

    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Paso 3: Construir la imagen de Docker
      - name: Build Docker image
        run: docker build -t taller-autos .

      # Paso 4: Ejecutar pruebas dentro del contenedor
      - name: Run tests in Docker
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Usa la URI de MongoDB Atlas
        run: |
          docker run --rm --env MONGO_URI=$MONGO_URI taller-autos npm test -- --coverage

      # Paso 5: Verificar cobertura de pruebas
      - name: Check coverage
        run: |
          # Crear un contenedor temporal para copiar el archivo de cobertura
          docker create --name test-container taller-autos
          # Copiar el archivo de cobertura desde el contenedor al host
          docker cp test-container:/app/coverage ./coverage
          # Eliminar el contenedor temporal
          docker rm test-container

          # Verificar la cobertura
          if [ $(grep -oP '(?<=All files\s+\|\s+)\d+' coverage/lcov-report/index.html) -lt 60 ]; then
            echo "Cobertura insuficiente (menos del 60%)"
            exit 1
          fi